
'use strict';
const $ = s => document.querySelector(s), esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const STORE = 'adhd-fairy-final-v4'; let saved = null, saveError = false, demoFixture = false;
try { saved = JSON.parse(localStorage.getItem(STORE)); if (saved?.version !== 4) saved = null } catch (e) { saveError = true }
const initial = { page: 'today', energy: 'Medium', daily: [{ id: 'task-statistics', title: 'Statistics assignment', category: 'Anchor', done: false }, { id: 'task-email', title: 'Reply to one email', category: 'Maintenance', done: false }], quests: [{ id: 'quest-portfolio', title: 'Portfolio website', cover: 'lavender', steps: [{ id: 'step-description', title: 'Write its description', done: false }, { id: 'step-screenshot', title: 'Add screenshots', done: false }, { id: 'step-publish', title: 'Publish it', done: false }], completed: false }], activeQuest: 'quest-portfolio', inbox: ['Email my professor', 'A video idea for later'], savedNotes: [], someday: [], chat: [['fairy', 'Let’s choose one little step.']], draft: '', quiet: false, compact: false, hidden: false, review: -1, session: false, outcome: '', wrapNotes: [] };
const S = Object.assign(structuredClone(initial), saved?.app || {}); S.page = 'today';
let R = saved?.charms || Charms.fresh();
const pages = {};
function currentQuest() { return S.quests.find(q => q.id === S.activeQuest) || S.quests[0] }
function dayKey() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
function saveAll() { if (demoFixture || window.isBloomFixture?.()) return true; try { localStorage.setItem(STORE, JSON.stringify({ version: 4, app: S, charms: R, garden: window.getGarden?.() || saved?.garden })); saveError = false; return true } catch (e) { saveError = true; toast('Could not save on this device. Keep this window open and try again.'); return false } }
function reward(type, id, day = dayKey()) { R = Charms.record(R, { type, id, day }, Date.now()); }
function finishAction() { const ok = saveAll(); render(); if (ok) celebrate() }
function composer(kind, placeholder, voice = false) { const control = voice ? `<div class="composer-input"><textarea name="message" rows="1" aria-label="${placeholder}" placeholder="${placeholder}" required>${kind === 'chat' ? esc(S.draft) : ''}</textarea><button type="button" class="voice-button" data-voice aria-label="Record voice"><img src="../assets/microphone.png" alt="" aria-hidden="true"></button></div><span class="voice-status" data-voice-status aria-live="polite"></span>` : `<textarea name="message" rows="1" aria-label="${placeholder}" placeholder="${placeholder}" required>${kind === 'chat' ? esc(S.draft) : ''}</textarea>`; return `<form class="composer" data-form="${kind}">${control}<button class="primary" aria-label="Send">➤</button></form>` }
function rail(f = false) { return `<aside class="rail">${scene(f)}<div class="card">${pixel('book', 'reward-art')}<h3>${f ? 'Something Magical' : 'Your next adventure'}</h3><p>${f ? 'Finish your first quest to earn a potion charm.' : 'One small step at a time.'}</p>${btn('Open Quest', 'go:quest')}</div></aside>` }
function scene(f = false) { return `<div class="scene ${f ? 'forest' : ''}" role="img" aria-label="${f ? 'Fairy in an enchanted forest' : 'Fairy in her magical library'}"></div>` }
function render() { let selected = ['quest', 'questcreate'].includes(S.page) ? 'quests' : ['discover', 'garden'].includes(S.page) ? 'collection' : S.page; $('#nav').innerHTML = [['today', 'Today'], ['talk', 'Talk'], ['inbox', 'Inbox'], ['quests', 'Quests'], ['collection', 'Collection'], ['settings', 'Settings']].map(([id, t], i) => `${i === 4 ? '<div class="spacer"></div>' : ''}<button data-action="go:${id}" class="${selected === id ? 'active' : ''}" ${selected === id ? 'aria-current="page"' : ''}>${pixel(id, 'nav-art')}${t}</button>`).join(''); $('#main').innerHTML = (saveError ? '<p role="alert" class="save-warning">Changes are in memory. Saving failed. <button data-action="retry">Retry save</button></p>' : '') + (pages[S.page]?.() || ''); $('#preview').value = S.page; wireFairy() }
function go(p) { S.page = p; render(); celebrate() }
function clock() { return window.bloomClock?.() || '25:00' }
function modal(html) { $('#dialog').className = ''; $('#dialog').innerHTML = html; $('#dialog').showModal() }
function quickChat() { return '' }
async function askNeurofairy(message) {
    const response = await fetch('/api/chat', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            message: message
        })
    });

    if (!response.ok) {
        throw new Error('Neurofairy could not respond.');
    }

    return response.json();
}
function pixel(id, cls = 'pixel-art') {
    const map = { matcha: 0, coffee: 1, mug: 1, book: 2, chapter: 2, quests: 2, quest: 2, potion: 3, thought: 3, greenbook: 4, settings: 4, rosebook: 5, rug: 5, lantern: 6, lamp: 6, today: 6, crystal: 7, collection: 7, star: 8, spark: 8, moon: 9, return: 9, rain: 9, letter: 10, talk: 10, basket: 11, inbox: 11 };
    const i = map[id] ?? 2; return `<span class="pixel-art ${cls}" aria-hidden="true" style="--col:${i % 4};--row:${Math.floor(i / 4)}"></span>`;
}


let toastTimer; function toast(t) { $('#toast').textContent = t; $('#toast').style.display = 'block'; clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').style.display = 'none', 3000) }
function btn(t, a, c = '') { return `<button class="${c}" data-action="${a}">${t}</button>` } function scene(f = false) { return `<div class="scene ${f ? 'forest' : ''}" role="img" aria-label="${f ? 'Fairy exploring an enchanted forest with a map' : 'Fairy reading a spellbook in her magical library'}"></div>` }
function layout(content, f = false) { if (S.page === 'talk') return `<section class="work chatwork">${content}</section>`; if (S.page === 'inbox') return `<section class="work inboxwork">${content}<div class="inboxfairy" aria-label="Fairy nearby" role="img"><img class="fairy-image" src="../assets/fairy-full.png" alt=""></div></section>`; return `<div class="layout"><section class="work">${content}</section>${rail(f)}</div>` }
function progress(n, d) { return `<div class="bar" role="progressbar" aria-label="Progress" aria-valuemin="0" aria-valuemax="${d}" aria-valuenow="${n}"><span style="width:${n / d * 100}%"></span></div>` }
function energy() { return `<p class="small muted">How’s your energy today?</p><div class="energy">${['Low', 'Medium', 'High', 'Survival'].map(x => `<button data-action="energy:${x}" aria-pressed="${S.energy === x}">${x}</button>`).join('')}</div>` }
function insights() { return layout(`<h1>Things you might notice</h1><p class="muted">Observations you can question, edit, or dismiss.</p><div class="listempty"><h3>No insights yet</h3><p>Fairy will only show patterns supported by information you chose to share.</p></div><div class="card"><h3>Your progress</h3><p>${(currentQuest()?.steps.filter(s => s.done).length || 0)} portfolio steps completed.</p>${btn('View Quest', 'go:quest')}</div>`) }
function wireFairy() { let f = $('#floating'); if (!f) return; const p = $('#peek'); f.addEventListener('mouseenter', () => p.classList.add('visible')); f.addEventListener('mouseleave', () => p.classList.remove('visible')); f.addEventListener('focus', () => p.classList.add('visible')); f.addEventListener('blur', () => p.classList.remove('visible')); let drag = null, moved = false; f.addEventListener('pointerdown', e => { drag = { x: e.clientX, y: e.clientY, left: f.offsetLeft, top: f.offsetTop }; moved = false; f.setPointerCapture(e.pointerId) }); f.addEventListener('pointermove', e => { if (!drag) return; let dx = e.clientX - drag.x, dy = e.clientY - drag.y; if (Math.abs(dx) + Math.abs(dy) > 5) moved = true; if (moved) { f.style.left = Math.max(0, Math.min(f.parentElement.clientWidth - f.offsetWidth, drag.left + dx)) + 'px'; f.style.top = Math.max(0, Math.min(f.parentElement.clientHeight - f.offsetHeight, drag.top + dy)) + 'px'; f.style.right = 'auto'; f.style.bottom = 'auto'; p.classList.remove('visible') } }); f.addEventListener('pointerup', () => drag = null); f.addEventListener('pointercancel', () => drag = null); f.addEventListener('click', () => { if (!moved) { $('#quick').hidden = false; $('#quick textarea').focus() } }) }
function heading(art, title, sub) { return `<div class="page-heading">${pixel(art, 'heading-art')}<div><h1>${title}</h1><p class="muted">${sub}</p></div></div>` }
function dayRows() { return S.daily.map(t => `<div class="day-row ${t.done ? 'done' : ''}"><label><input type="checkbox" data-day="${t.id}" ${t.done ? 'checked' : ''}><span><span class="eyebrow">${t.category}</span><span class="task-name">${esc(t.title)}</span></span></label><button class="ghost" data-v2="edit-day:${t.id}" aria-label="Edit ${esc(t.title)}">Edit</button><button class="ghost" data-v2="remove-day:${t.id}" aria-label="Remove ${esc(t.title)}">×</button></div>`).join('') }
pages.today = function () { return layout(`${heading('book', 'Welcome to your cottage', 'A little magic for today.')}${energy()}<div class="card featured nextstep"><div class="next-title">${pixel('book', 'inline-art')}<div><h3>Open your statistics assignment</h3><p>Just read the first question.</p></div></div><div class="actions">${btn('Start with me', 'go:focus', 'primary')}${btn('Make it smaller', 'smaller')}</div></div><div class="section-heading"><h2>Today’s plan</h2><button data-v2="add-day" class="small-button">+ Add task</button></div><div id="day-list">${dayRows()}</div><form class="day-add" data-v2-form="day"><input aria-label="New daily task" name="title" placeholder="What else would you like to do today?" required><select name="category" aria-label="Task category"><option>Optional</option><option>Anchor</option><option>Quest</option><option>Maintenance</option></select><button class="primary">Add</button></form><p class="small muted">Your plan can change. Add, edit, or remove tasks anytime.</p>${composer('capture', 'Save a thought for later…')}`) };
function chatMessages() { return S.chat.map(([role, t]) => `<div class="message-line ${role}">${role === 'fairy' ? '<img class="message-avatar" src="../assets/fairy-full.png" alt="Fairy">' : ''}<div class="message-body">${esc(t)}</div></div>`).join('') }
pages.talk = function () { return `<section class="chatwork">${heading('letter', 'Talk with Fairy', 'A little room to untangle your thoughts.')}<div class="chat-panel"><div class="conversation-label">Today’s conversation <span class="small muted">Demo · scripted replies</span></div><div class="chat-transcript">${chatMessages()}</div><div class="capture-suggestion">${pixel('basket', 'inline-art')}<div><h3>Capture first. Organize later.</h3><p>Set a thought down without deciding what to do with it yet.</p></div><button data-v2="save-chat">Save to Inbox</button></div><div class="chat-tools">${btn('Brain dump', 'prompt:Brain dump')}${btn('Plan my day', 'prompt:Plan my day')}${btn('I’m stuck', 'prompt:I’m stuck')}</div>${composer('chat', 'What’s on your mind?', true)}</div></section>` };
pages.inbox = function () { return `<section class="inboxwork">${heading('basket', 'A place for your thoughts', 'Saved here. Not added to today.')}<div class="capture-desk">${pixel('letter', 'capture-art')}<div><label class="eyebrow" for="capture-thought">A LITTLE NOTE FOR LATER</label><form class="composer" data-form="capture"><input type="text" id="capture-thought" aria-label="Drop a thought here" placeholder="Drop a thought here…" required><button class="primary">Save thought</button></form></div></div><div class="section-heading"><h2>${S.inbox.length} unsorted thoughts</h2><span class="small muted">Review when you’re ready</span></div><div class="inbox-notes">${S.inbox.map((t, i) => `<article class="note-row">${pixel(i % 3 === 0 ? 'letter' : i % 3 === 1 ? 'greenbook' : 'rosebook', 'note-art')}<div class="note-content"><div class="note-title"><strong>${esc(t)}</strong>${btn(S.review === i ? 'Close' : 'Review', `review:${i}`)}</div><p class="small muted">A thought to keep, turn into a task, or explore.</p>${S.review === i ? `<div class="note-review"><label>Where would you like to keep it?<select id="destination"><option>Task</option><option>Quest</option><option>Someday</option><option>Note</option></select></label><div class="actions"><button data-v2="sort-note:${i}" class="primary">Save destination</button>${btn('Keep here', 'keep')}</div><p class="small muted">Saving as a task adds it to Today as Optional. Other choices stay unscheduled.</p></div>` : ''}</div></article>`).join('') || '<div class="listempty">Your basket is clear. Drop in a thought whenever you like.</div>'}</div>${S.savedNotes.length + S.someday.length ? `<details class="saved-thoughts"><summary>Saved for later · ${S.savedNotes.length + S.someday.length}</summary>${S.savedNotes.concat(S.someday).map(t => `<p>${esc(t)}</p>`).join('')}</details>` : ''}<div class="inbox-companion"><img class="fairy-image" src="../assets/fairy-full.png" alt="Fairy floating nearby"><span>One thought at a time.</span></div></section>` };
pages.companion = function () { return `${heading('star', 'A little magic nearby', 'Hover or focus for a peek. Click to chat.')}<div class="companiongrid"><div><div class="desktop"><p class="small muted">Desktop preview · drag the fairy here</p><div class="peek" id="peek"><strong>Statistics assignment</strong><br><span class="small">${clock()} left · Focusing together</span></div><button class="floating" id="floating" aria-label="Open Fairy chat" ${S.hidden ? 'hidden' : ''}>${S.compact ? pixel('star', 'compact-art') : '<img class="fairy-image" src="../assets/fairy-full.png" alt="">'}</button></div><div class="actions">${btn(S.compact ? 'Use fairy' : 'Use compact icon', 'compact')}${btn(S.hidden ? 'Show fairy' : 'Hide fairy', 'hide')}</div></div>${quickChat()}</div>` };
pages.widget = function () { return `${heading('star', 'A little window of magic', 'App icon and compact desktop widget.')}<div class="widget-showcase"><section class="appicon-preview"><img src="../assets/app-icon.png" alt="ADHD Fairy app icon"><h2>ADHD Fairy</h2><p class="muted">Wing, star, and spellbook.</p></section><section class="desktop-widget"><header>${pixel('star', 'tiny-art')}<strong>ADHD Fairy</strong></header><div class="widget-content"><div><span class="eyebrow">One small step</span><h3>Read question one</h3><p class="small muted">Statistics assignment</p><button data-action="quickstart" class="primary">Start with me</button></div><img src="../assets/fairy-full.png" alt="Fairy"></div><footer>${btn('Open cottage', 'go:today', 'ghost')}</footer></section></div><p class="small muted">Interactive browser concept. A native WidgetKit extension is a separate implementation step.</p>` };
const widgetOption = document.createElement('option'); widgetOption.value = 'widget'; widgetOption.textContent = 'App icon & widget'; $('#preview').append(widgetOption);
function taskDialog(id) { let t = S.daily.find(x => x.id === id); modal(`<h2>${t ? 'Edit task' : 'Add to today'}</h2><form data-v2-form="taskdialog" data-id="${t?.id || ''}"><label>Task<input type="text" name="title" value="${esc(t?.title || '')}" required placeholder="One thing you’d like to do"></label><label class="field-label">Category<select name="category">${['Optional', 'Anchor', 'Quest', 'Maintenance'].map(c => `<option ${c === t?.category ? 'selected' : ''}>${c}</option>`).join('')}</select></label><div class="actions"><button class="primary">Save task</button><button type="button" data-action="cancel">Cancel</button></div></form>`) } let spriteSequence = 0; function sprite(atlas, i, cls = '') { const a = SPRITES[atlas], r = a.rects[i], clip = 'spriteclip' + (++spriteSequence); return `<svg class="asset-sprite ${cls}" viewBox="${r.join(' ')}" preserveAspectRatio="xMidYMax meet" aria-hidden="true"><defs><clipPath id="${clip}"><rect x="${r[0]}" y="${r[1]}" width="${r[2]}" height="${r[3]}"/></clipPath></defs><image href="${ASSET_URLS[atlas]}" width="${a.width}" height="${a.height}" clip-path="url(#${clip})"/></svg>` }
function charmArt(id, cls = '') { return sprite('charms', Charms.catalog.find(c => c.id === id).art, cls) }
const covers = ['lavender', 'moss', 'rose', 'midnight', 'honey', 'sky'];
function bookArt(id, cls = '') { return sprite('book-covers', Math.max(0, covers.indexOf(id)), cls) }
function collectionTabs(active) { return `<div class="collection-tabs" role="navigation" aria-label="Collection sections">${[['collection', 'Your charms'], ['discover', 'Discover'], ['garden', 'Garden']].map(([id, label]) => `<button data-action="go:${id}" ${active === id ? 'aria-current="page"' : ''}>${label}</button>`).join('')}</div>` }
function shelfRow(charms, first) { return `<div class="shelf-row"><div class="shelf-objects">${charms.map(c => `<button class="shelf-charm" data-charm="${c.id}" aria-label="${esc(c.name)}. View charm">${charmArt(c.id)}${R.unlocked.find(x => x.id === c.id)?.seen === false ? '<span class="new-marker">New</span>' : ''}</button>`).join('')}${first ? '<div class="shelf-fairy"><img src="../assets/fairy-seated.png" alt="Fairy sitting on your shelf"></div>' : ''}</div><div class="wood-shelf" aria-hidden="true"></div><div class="shelf-labels">${charms.map(c => `<span>${c.name}</span>`).join('')}</div></div>` }
pages.collection = function () { const earned = R.unlocked.map(u => Charms.catalog.find(c => c.id === u.id)).filter(Boolean); let rows = []; rows.push(shelfRow(earned.slice(0, 3), true)); for (let i = 3; i < earned.length; i += 4)rows.push(shelfRow(earned.slice(i, i + 4), false)); if (rows.length === 1) rows.push(shelfRow([], false)); return `<section class="collection-work">${heading('crystal', 'Your charms shelf', 'Little treasures from your adventures.')}${collectionTabs('collection')}<div class="shelf-panel">${rows.join('')}${!earned.length ? '<p class="shelf-empty">Your shelf is waiting for its first little treasure.<br><span>Complete your first task to earn a star.</span></p>' : ''}</div></section>` };
pages.discover = function () { const remaining = Charms.catalog.filter(c => !R.unlocked.some(x => x.id === c.id)); return `<section class="collection-work">${heading('crystal', 'Discover charms', 'Little treasures to look forward to.')}${collectionTabs('discover')}<h2 class="discover-title">Still to discover</h2><div class="discover-grid">${remaining.map(c => `<article class="discover-card">${charmArt(c.id)}<div><h3>${c.name}</h3><p>${Charms.requirement(c)}</p><progress max="${c.threshold}" value="${Math.min(c.threshold, R[c.metric].length)}" aria-label="${esc(c.name)} progress"></progress><span class="metric">${Math.min(c.threshold, R[c.metric].length)} / ${c.threshold} ${c.metric}</span></div></article>`).join('')}</div>${remaining.length ? '<p class="collection-note">Charms appear on your shelf automatically when earned.</p>' : '<p class="collection-note">You’ve discovered every charm in this collection.</p>'}</section>` };
function coverPicker(selected) { return `<fieldset class="cover-picker"><legend>Choose your cover</legend><p>All covers are yours. Change it anytime.</p><div class="cover-grid">${covers.map(c => `<label class="cover-choice"><input type="radio" name="cover" value="${c}" ${c === selected ? 'checked' : ''}><span class="cover-check" aria-hidden="true">✓</span>${bookArt(c)}<span>${c[0].toUpperCase() + c.slice(1)}</span></label>`).join('')}</div></fieldset>` }
function questForm(q) { return `<h2>${q ? 'Your quest book' : 'A new adventure'}</h2><p>Every quest begins with a little book.</p><form data-form="quest" data-id="${q?.id || ''}"><label>Quest name<input name="title" value="${esc(q?.title || '')}" maxlength="120" placeholder="Name your adventure" required></label>${coverPicker(q?.cover || 'lavender')}<div class="actions"><button type="button" data-action="cancel">Cancel</button><button class="primary">${q ? 'Save changes' : 'Create quest'}</button></div></form>` }
function questModal(q) { modal(questForm(q)); $('#dialog').className = 'quest-modal'; }
pages.questcreate = () => `<section class="quest-create-preview">${questForm()}</section>`;
pages.quests = () => layout(`${heading('book', 'Your quest books', 'An adventure, one small step at a time.')}<div class="quest-books">${S.quests.map(q => `<button class="quest-book" data-open-quest="${q.id}">${bookArt(q.cover, 'book-cover')}<h3>${esc(q.title)}</h3><p>${q.completed ? 'Completed' : q.steps.length ? `${q.steps.filter(s => s.done).length} of ${q.steps.length} steps complete` : 'Draft · find your first step'}</p>${q.steps.length ? progress(q.steps.filter(s => s.done).length, q.steps.length) : ''}<span>Open Quest →</span></button>`).join('')}<button class="quest-book new-book" data-action="newquest">${bookArt('moss', 'book-cover')}<h3>A new adventure</h3><p>Begin with a name.</p><span>+ Create Quest</span></button></div>`, true);
pages.quest = function () { const q = currentQuest(); if (!q) return pages.quests(); const n = q.steps.filter(x => x.done).length; return layout(`<div class="quest-heading">${bookArt(q.cover)}<div><h1>${esc(q.title)}</h1><button data-action="editquest">Edit name & cover</button></div></div>${q.steps.length ? progress(n, q.steps.length) : '<p>Your book is ready for its first step.</p>'}<p>${n} of ${q.steps.length} steps complete</p>${q.steps.map(s => `<label class="row"><input type="checkbox" data-quest-step="${s.id}" ${s.done ? 'checked' : ''}><span>${esc(s.title)}</span></label>`).join('')}<form class="day-add" data-form="step"><input name="title" aria-label="New quest step" placeholder="One small step…" required><button>Add step</button></form><div class="actions">${btn('Start with me', 'go:focus', 'primary')}${q.completed ? '<span>Quest completed. Your book stays here.</span>' : n && n === q.steps.length ? btn('Finish Quest', 'finishquest') : ''}</div>${composer('chat', 'Ask Fairy about this quest…')}`, true) };
pages.wrap = () => layout(`<h1>A little step counts.</h1><p>Save a place to come back to.</p><div class="card"><h2>How did it go?</h2><div class="actions">${['Made progress', 'Got stuck', 'Needed to stop'].map(x => `<button data-action="outcome:${x}" aria-pressed="${S.outcome === x}">${x}</button>`).join('')}</div><label for="returnpoint">Where would you like to pick up?</label><textarea id="returnpoint" placeholder="Optional return point"></textarea><p class="small muted">Task completion stays separate from saving a focus session.</p><div class="actions">${btn('Save and close', 'savewrap', 'primary')}${btn('Skip', 'go:today')}</div></div>`);
pages.settings = () => layout(`<h1>Make yourself at home</h1><p>You choose how Fairy accompanies you.</p><label class="settingsrow"><span>Quiet celebrations</span><input type="checkbox" data-setting="quiet" ${S.quiet ? 'checked' : ''}></label><p class="small muted">Charms still unlock. Congratulations popups stay quiet.</p><h2>Privacy & context</h2><p>No calendar, email, or account is connected in this prototype.</p>${btn('View insights', 'go:insights')}<h2>Desktop companion</h2>${btn('Preview companion', 'go:companion')}<p class="small muted">Reduced motion follows your system setting. Sound is off.</p>`);
pages.insights = insights;
let announced = [];
function celebrate() { if (!R.pending.length || $('#dialog').open || window.focusIsRunning?.() || demoFixture) return; if (S.quiet) { R = Charms.acknowledge(R, R.pending); saveAll(); return; } if (!saveAll()) return; announced = [...R.pending]; modal(`<div class="congrats"><h2>A little magic, earned!</h2><div class="earned-list">${announced.map(id => { const c = Charms.catalog.find(c => c.id === id); return `<div>${charmArt(id)}<h3>${c.name}</h3><p>${Charms.requirement(c)} · complete</p></div>` }).join('')}</div><p>Added to your charms shelf.</p><div class="actions"><button class="primary" data-action="congratsclose">Lovely!</button><button data-action="congratsshelf">View shelf</button></div></div>`); $('#dialog').className = 'congrats-modal'; }
function acknowledgeCelebration() { if (announced.length) { R = Charms.acknowledge(R, announced); announced = []; saveAll() } }
$('#dialog').addEventListener('cancel', acknowledgeCelebration);
$('#dialog').addEventListener('close', () => { acknowledgeCelebration(); $('#dialog').className = ''; });
function charmDetails(id) { const c = Charms.catalog.find(c => c.id === id), u = R.unlocked.find(x => x.id === id); if (!c || !u) return; R = Charms.seen(R, id); saveAll(); modal(`<div class="charm-detail">${charmArt(id)}<h2>${c.name}</h2><p>${Charms.requirement(c)} · complete</p><p>Earned ${new Date(u.earnedAt).toLocaleDateString()}</p>${btn('Back to shelf', 'cancel')}</div>`); }
document.addEventListener('input', e => { if (e.target.closest('[data-form="chat"]')) { S.draft = e.target.value; saveAll() } });
document.addEventListener('click', e => {
    const charm = e.target.closest('[data-charm]'); if (charm) { charmDetails(charm.dataset.charm); return; } const quest = e.target.closest('[data-open-quest]'); if (quest) { S.activeQuest = quest.dataset.openQuest; go('quest'); return; } const b = e.target.closest('[data-action],[data-v2]'); if (!b) return; let [a, ...rest] = (b.dataset.action || b.dataset.v2).split(':'), v = rest.join(':');
    if (a === 'go') { go(v); return; } if (a === 'cancel' || a === 'congratsclose') { acknowledgeCelebration(); $('#dialog').close(); return; } if (a === 'congratsshelf') { acknowledgeCelebration(); $('#dialog').close(); go('collection'); return; } if (a === 'retry') { finishAction(); return; } if (a === 'energy') S.energy = v;
    if (a === 'smaller') { modal(`<h2>One smaller step</h2><p>Open the assignment file. That’s enough for a start.</p>${btn('Try this', 'acceptsmall', 'primary')}${btn('Keep original', 'cancel')}`); return; } if (a === 'acceptsmall') { $('#dialog').close(); go('focus'); return; }
    if (a === 'prompt') { S.chat.push(['user', v], ['fairy', 'Let’s choose one small thing. What would you like to set down first?']); reward('chat'); }
    if (a === 'review') S.review = +v; if (a === 'keep') S.review = -1;
    if (a === 'sort-note') { const dest = $('#destination').value, t = S.inbox[+v]; if (dest === 'Task') S.daily.push({ id: crypto.randomUUID(), title: t, category: 'Optional', done: false }); if (dest === 'Quest') S.quests.push({ id: crypto.randomUUID(), title: t, cover: 'lavender', steps: [], completed: false }); if (dest === 'Note') S.savedNotes.push(t); if (dest === 'Someday') S.someday.push(t); S.inbox.splice(+v, 1); S.review = -1; }
    if (a === 'add-day') { taskDialog(); return; } if (a === 'edit-day') { taskDialog(v); return; } if (a === 'remove-day') S.daily = S.daily.filter(x => String(x.id) !== v);
    if (a === 'save-chat') { const last = [...S.chat].reverse().find(x => x[0] === 'user'); if (last) { S.inbox.unshift(last[1]); reward('capture'); } }
    if (a === 'newquest' || a === 'new-quest') { questModal(); return; } if (a === 'editquest') { questModal(currentQuest()); return; }
    if (a === 'finishquest') { const q = currentQuest(); if (q?.steps.length && q.steps.every(s => s.done) && !q.completed) { q.completed = true; reward('quest', q.id); } }
    if (a === 'outcome') { S.outcome = v; document.querySelectorAll('[data-action^="outcome:"]').forEach(el => el.setAttribute('aria-pressed', el === b)); saveAll(); return; }
    if (a === 'savewrap') { if (!S.outcome) { toast('Choose how it went, or skip.'); return; } S.wrapNotes.push({ outcome: S.outcome, note: $('#returnpoint').value, at: Date.now() }); S.session = false; S.outcome = ''; S.page = 'today'; }
    if (a === 'compact') S.compact = !S.compact; if (a === 'hide') S.hidden = !S.hidden; if (a === 'closequick') { $('#quick').hidden = true; return; } finishAction();
});
document.addEventListener('change', e => { if (e.target.dataset.day) { const t = S.daily.find(x => String(x.id) === e.target.dataset.day); t.done = e.target.checked; if (t.done) reward('task', t.id); finishAction(); } if (e.target.dataset.questStep) { const s = currentQuest().steps.find(s => s.id === e.target.dataset.questStep); s.done = e.target.checked; if (s.done) reward('task', s.id); finishAction(); } if (e.target.dataset.setting) { S[e.target.dataset.setting] = e.target.checked; finishAction(); } });
document.addEventListener('submit', async e => {
    const f = e.target, kind = f.dataset.form || f.dataset.v2Form; if (!kind) return; e.preventDefault(); const data = new FormData(f); const title = String(data.get('title') || '').trim(); if (['quest', 'step', 'day', 'taskdialog'].includes(kind) && !title) return;
    if (kind === 'quest') { const q = S.quests.find(q => q.id === f.dataset.id), cover = String(data.get('cover')); if (!covers.includes(cover)) return; if (q) { q.title = title; q.cover = cover } else { S.quests.push({ id: crypto.randomUUID(), title, cover, steps: [], completed: false }); } if ($('#dialog').open) $('#dialog').close(); S.page = 'quests'; }
    else if (kind === 'step') { currentQuest().steps.push({ id: crypto.randomUUID(), title, done: false }); currentQuest().completed = false; }
    else if (kind === 'day' || kind === 'taskdialog') { const t = S.daily.find(x => String(x.id) === f.dataset.id); const category = String(data.get('category') || 'Optional'); if (t) { t.title = title; t.category = category } else S.daily.push({ id: crypto.randomUUID(), title, category, done: false }); if ($('#dialog').open) $('#dialog').close(); }
    else {
        const input = f.querySelector('textarea,input');
        const t = input.value.trim();

        if (!t) return;

        if (kind === 'capture') {
            S.inbox.unshift(t);
            reward('capture');
            toast('Saved to Inbox. Not added to today.');
        } else {
            S.chat.push(['user', t]);
            S.draft = '';
            reward('chat');
            finishAction();

            try {
                const result = await askNeurofairy(t);
                S.chat.push(['fairy', result.reply]);
            } catch (error) {
                S.chat.push([
                    'fairy',
                    'I’m having trouble connecting right now. Your thought is still here, and you can try again in a moment.'
                ]);
            }

            finishAction();
            return;
        }
    }

    finishAction();
});
$('#preview').addEventListener('change', e => go(e.target.value));
